CREATE OR REPLACE PROCEDURE INSERT_JEDI(ID NUMERIC, JEDI_NAME VARCHAR, SABER_COLOR VARCHAR)
AS
$$
	BEGIN
		INSERT INTO JEDI VALUES(ID, JEDI_NAME, SABER_COLOR);
	END
$$
LANGUAGE plpgsql

SELECT VERSION ();